name: tests
on: push
jobs:
  tests:
    # runs-on: self-hosted
    runs-on: ubuntu-22.04
    container: rutsky/cpp-test:20
    steps:
      - uses: actions/checkout@v3
      - run: ./run_tests.sh
  clang-tidy:
    # runs-on: self-hosted
    runs-on: ubuntu-22.04
    container: rutsky/cpp-test:20
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "OPTIONAL: clang-tidy checks the source code for typical errors, style guide conformance or C++ misuse."
          clang-tidy \
            '--checks=readability-inconsistent-declaration-parameter-name,modernize-deprecated-headers,modernize-use-noexcept,modernize-use-override,cppcoreguidelines-pro-type-cstyle-cast,google-readability-casting,readability-delete-null-pointer,readability-redundant-control-flow,fuchsia-restrict-system-includes' \
            '--config={CheckOptions: [{key: fuchsia-restrict-system-includes.Includes, value: "*,-bits/*"}]}' \
            --quiet \
            '--warnings-as-errors=*' \
            dict.hpp dict_serialization.hpp dict_json.hpp \
            -- \
            -std=c++20 \
            -Wall -Wextra
